# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "xzxg001"
url = "https://github.com/xzxg001"

[social.params]
icon = "brand-github"

[[social]]
identifier = "csdn"
name = "xzxg001"
url = "https://blog.csdn.net/xzxg001"

[social.params]
icon = "brand-csdn"
